version: "3.8"

services:
  frontend:
    build: ./MagnePlay-Frontend
    image: sebastianvi1/magnetplay-frontend:v1
    ports:
      - "5173:5173"
    volumes:
      - ./MagnePlay-Frontend/src:/app/src
    depends_on:
      - backend
      - streaming-api

  torrent-api:
    build: ./Torrent-Api-py
    image: sebastianvi1/torrent-scrapper:v1
    ports:
      - "8009:8009"

  backend:
    build: ./MagnetPlay-Backend
    image: sebastianvi1/magnetplay-backend:v1
    depends_on:
      - torrent-api
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/magnetPlay
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123sebass

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123sebass
      - POSTGRES_DB=magnetPlay
    ports:
      - "5432:5432"

  streaming-api:
    build: ./Streaming_Api
    image: sebastianvi1/streaming-api:v1
    ports:
      - "3000:3000"
    volumes:
      - ./Streaming_Api:/app
    command: npx nodemon src/server.js
